# Serverpod password configuration template
# Copy this file to passwords.yaml and replace with your actual passwords
# IMPORTANT: Never commit passwords.yaml to version control!

development:
  database: "your_development_database_password"
  redis: "your_development_redis_password"

test:
  database: "your_test_database_password"
  redis: "your_test_redis_password"

staging:
  database: "your_staging_database_password"
  redis: "your_staging_redis_password"

production:
  database: "your_production_database_password"
  redis: "your_production_redis_password"