name: zenvestor_domain
description: Shared domain layer for Zenvestor - contains core business logic, value objects, and domain entities
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  equatable: ^2.0.5
  fpdart: ^1.1.0
  uuid: ^4.4.0

dev_dependencies:
  test: ^1.25.0
  mocktail: ^1.0.0
  lints: ^3.0.0