include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/src/generated/**
    - test/integration/test_tools/serverpod_test_tools.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
