services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: zenvestor
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - zenvestor_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: zenvestor_test
      POSTGRES_PASSWORD: "${POSTGRES_TEST_PASSWORD}"
    volumes:
      - zenvestor_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "${REDIS_TEST_PASSWORD}"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  zenvestor_data:
  zenvestor_test_data:
