name: zenvestor_server
description: Starting point for a Serverpod server.
version: 0.0.0
homepage: https://zenvestor.app
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  equatable: ^2.0.7
  fpdart: ^1.1.1
  meta: ^1.17.0
  serverpod: 2.9.1
  uuid: ^4.2.1
dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  mocktail: ^1.0.4
  serverpod_test: 2.9.1
  test: '^1.24.2'
  very_good_analysis: ^9.0.0
